"""Fix guest-appearance relationship

Revision ID: 234777d62d9c
Revises: a8aa029a696a
Create Date: 2025-06-22 14:24:53.988960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234777d62d9c'
down_revision = 'a8aa029a696a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
